#ifndef CONFIG_H
#define CONFIG_H

enum LEDS_PINS
{
	RED_LED_PIN = 12,
	GREEN_LED_PIN
};

enum BUTTONS_PINS
{
	BUTTON_PIN = 5,
	INCREMENT_BUTTON_PIN,
	DECREMENT_BUTTON_PIN
};

#define DEBOUNCE_TIME 								150

#define LED_TASK_OFFSET 							1
#define LED_TASK_RECURRENCE 						200

#define BUTTON_TASK_OFFSET 							5
#define BUTTON_TASK_RECURRENCE 						100

#define BLINK_LED_TASK_OFFSET 						9
#define BLINK_LED_TASK_RECURRENCE 					500

#define CHANGE_BLINK_FREQUENCY_TASK_OFFSET 			3
#define CHANGE_BLINK_FREQUENCY_TASK_RECURRENCE 		100

#define IDLE_TASK_OFFSET 							0
#define IDLE_TASK_RECURRENCE 						1000

#endif